//NOTE: This file is automatically generated by /home/yuval/MYTREE/Programming Projects/Go Projects/kafka-postman/build.sh
    package main

    func GetMyVersion() string {
    	return "v0.0.205.1611123818"
    }
