//NOTE: This file is automatically generated by /mnt/ext_disk/MYTREE/Programming Projects/Go Projects/kafka-postman/build.sh
package main

func GetMyVersion() string {
	return "v0.0.186.1599366530"
}
